services:
  v2bx:
    build:
      context: ../  # 这里把当前路径的上一级加到上下文环境中
      dockerfile: ./deploy/Dockerfile  #指定dockerfile
    image: crpi-r21td9yeapqngs0l.cn-chengdu.personal.cr.aliyuncs.com/coterjiesen/v2bx:0.0.3  # You can specify a different version if needed
    container_name: v2bx

    ports:
      - "443:443" 
    volumes:
      - ./config.json:/etc/V2bX/config.json
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/html:/etc/nginx/html
